services:
  texas-poker-api:
    build:
      context: ./texas-poker-backend/
      dockerfile: Dockerfile.dev
    container_name: texas-poker-api
    volumes:
      - ./texas-poker-backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./envs/texas-poker-backend.env
    command: bash -c "bundle exec rails db:create db:migrate && bundle exec rails s -b 0.0.0.0 -p 3000"
    networks:
      - texas-poker-net

  postgres:
    image: postgres:15
    container_name: texas-poker-db
    env_file:
      - ./envs/texas-poker-backend.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - texas-poker-net

  redis:
    image: redis:7-alpine
    container_name: texas-poker-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes
    networks:
      - texas-poker-net

  texas-poker-client:
    build:
      context: ./texas-poker-client/
      dockerfile: Dockerfile
    container_name: texas-poker-client
    restart: unless-stopped
    depends_on:
      - texas-poker-api
    env_file:
      - ./envs/texas-poker-client.env
    ports:
      - "3050:3050"
    volumes:
      - ./texas-poker-client:/app
      - /app/node_modules
    networks:
      - texas-poker-net

networks:
  texas-poker-net:

volumes:
  pgdata:
  redisdata:
